<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Log extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Log_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('log/log_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Log_model->json();
    }

    public function read($id) 
    {
        $row = $this->Log_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nim' => $row->nim,
		'nomer_hp' => $row->nomer_hp,
		'tgl_diubah' => $row->tgl_diubah,
	    );
            $this->load->view('log/log_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('log'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('log/create_action'),
	    'id' => set_value('id'),
	    'nim' => set_value('nim'),
	    'nomer_hp' => set_value('nomer_hp'),
	    'tgl_diubah' => set_value('tgl_diubah'),
	);
        $this->load->view('log/log_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nim' => $this->input->post('nim',TRUE),
		'nomer_hp' => $this->input->post('nomer_hp',TRUE),
		'tgl_diubah' => $this->input->post('tgl_diubah',TRUE),
	    );

            $this->Log_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('log'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Log_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('log/update_action'),
		'id' => set_value('id', $row->id),
		'nim' => set_value('nim', $row->nim),
		'nomer_hp' => set_value('nomer_hp', $row->nomer_hp),
		'tgl_diubah' => set_value('tgl_diubah', $row->tgl_diubah),
	    );
            $this->load->view('log/log_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('log'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nim' => $this->input->post('nim',TRUE),
		'nomer_hp' => $this->input->post('nomer_hp',TRUE),
		'tgl_diubah' => $this->input->post('tgl_diubah',TRUE),
	    );

            $this->Log_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('log'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Log_model->get_by_id($id);

        if ($row) {
            $this->Log_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('log'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('log'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nim', 'nim', 'trim|required');
	$this->form_validation->set_rules('nomer_hp', 'nomer hp', 'trim|required');
	$this->form_validation->set_rules('tgl_diubah', 'tgl diubah', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Log.php */
/* Location: ./application/controllers/Log.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-09 16:15:28 */
/* http://harviacode.com */